name: Build under Windows

on: pull_request

jobs:
  build:
    name: Build under Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: gradle

      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2

      - name: Build project and run tests
        shell: cmd
        # For the reason on `--no-daemon` see https://github.com/actions/cache/issues/454
        run: gradlew.bat build --stacktrace --no-daemon
